fix displaying a slash
morpher-ru/gramdict pull request #163
Opened 2021-02-03 21:22 UTC by yntermench

Fix displaying a slash in file symbols.cshtml

2021-02-03 21:45 UTC, bzaar requested changes
Да, только **ый/ой** должны быть слева от большой черты, а **ий** - справа.

2021-02-04 07:22 UTC, yntermench reviewed
Fixed file symbol.cshtml

2021-02-04 12:49 UTC, bzaar requested changes
Теперь один **-ий** (левый) лишний:

![image](https://user-images.githubusercontent.com/4028922/106894806-56857f00-66e7-11eb-9214-fc7aac053cb6.png)

https://dev.gramdict.ru/declension/symbols#s1

2021-02-04 13:37 UTC, bzaar commented
Должно быть так:

![image](https://user-images.githubusercontent.com/4028922/106900124-0c53cc00-66ee-11eb-85e8-da08b8269e73.png)

2021-02-04 14:05 UTC, yntermench reviewed
Fifth fix symbols.cshtml

2021-02-04 15:20 UTC, bzaar requested changes
См. ниже. (Думаю, это последний штрих.)

2021-02-04 15:20 UTC, bzaar commented on gramdictru/Pages/declension/symbols.cshtml
> +                <span class="drob"><b>-ий</b></span>
Думаю, ```class="drob"``` тут можно убрать.

2021-02-25 19:23 UTC, merged